import React from 'react';
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Trash2, FileDown, GripVertical } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Choice {
  id: string;
  institute: string;
  program: string;
  category: string;
  closing_rank: number;
}

interface SidebarProps {
  choices: Choice[];
  setChoices: (choices: Choice[]) => void;
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
}

const SortableItem = ({ id, choice, onRemove }: { id: string, choice: Choice, onRemove: (id: string) => void }) => {
  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  return (
    <div ref={setNodeRef} style={style} className="bg-white/60 backdrop-blur-md border border-white/40 p-3 mb-2 rounded-xl shadow-sm flex items-center justify-between group">
      <div className="flex items-center gap-3 overflow-hidden">
        <div {...attributes} {...listeners} className="cursor-grab p-1 hover:bg-gray-100 rounded text-gray-400 group-hover:text-gray-600">
          <GripVertical size={16} />
        </div>
        <div className="flex-1 truncate">
          <p className="text-sm font-semibold text-gray-800 truncate">{choice.institute}</p>
          <p className="text-xs text-gray-500 truncate">{choice.program}</p>
        </div>
      </div>
      <button onClick={() => onRemove(id)} className="text-red-400 hover:text-red-600 p-1">
        <Trash2 size={16} />
      </button>
    </div>
  );
};

const CounselingSidebar: React.FC<SidebarProps> = ({ choices, setChoices, isOpen, setIsOpen }) => {
  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  const handleDragEnd = (event: any) => {
    const { active, over } = event;
    if (active.id !== over.id) {
      setChoices((items) => {
        const oldIndex = items.findIndex((i) => i.id === active.id);
        const newIndex = items.findIndex((i) => i.id === over.id);
        return arrayMove(items, oldIndex, newIndex);
      });
    }
  };

  const handleRemove = (id: string) => {
    setChoices(choices.filter(c => c.id !== id));
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text('My Counseling Choice List', 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Disclaimer: This list is based on previous year trends and is for informational purposes.', 14, 28);
    
    autoTable(doc, {
      startY: 35,
      head: [['Pref', 'Institute', 'Program', 'Category', 'Prev. Cutoff']],
      body: choices.map((c, index) => [
        index + 1,
        c.institute,
        c.program,
        c.category,
        c.closing_rank || 'N/A'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] },
    });

    const pageCount = doc.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text('Generated by UPTAC Predictor - Made by Tushar Bhardwaj', 14, doc.internal.pageSize.height - 10);
    }

    doc.save('My_Choice_List.pdf');
  };

  return (
    <div className={`fixed inset-y-0 right-0 w-80 sm:w-96 bg-white/80 backdrop-blur-xl border-l border-white/50 shadow-2xl transform transition-transform duration-300 ease-in-out z-50 flex flex-col ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}>
      <div className="p-5 border-b border-gray-200/50 flex justify-between items-center bg-white/50">
        <h2 className="text-lg font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">Counseling Flow</h2>
        <button onClick={() => setIsOpen(false)} className="text-gray-500 hover:text-gray-700">✕</button>
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        {choices.length === 0 ? (
          <div className="text-center text-gray-500 mt-10">
            <p>No choices added yet.</p>
            <p className="text-sm mt-2">Search and add colleges to your list.</p>
          </div>
        ) : (
          <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
            <SortableContext items={choices.map(c => c.id)} strategy={verticalListSortingStrategy}>
              {choices.map(choice => (
                <SortableItem key={choice.id} id={choice.id} choice={choice} onRemove={handleRemove} />
              ))}
            </SortableContext>
          </DndContext>
        )}
      </div>

      {choices.length > 0 && (
        <div className="p-4 border-t border-gray-200/50 bg-white/50 backdrop-blur-md">
          <button onClick={exportPDF} className="w-full py-3 px-4 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white rounded-xl shadow-lg shadow-indigo-200 flex items-center justify-center gap-2 transition-all">
            <FileDown size={18} /> Export as PDF
          </button>
        </div>
      )}
    </div>
  );
};

export default CounselingSidebar;
