interface CollegeData {
  institute: string;
  program: string;
  quota: string;
  category: string;
  round: string;
  opening_rank: number;
  closing_rank: number;
}

export const exportToCSV = (
  data: CollegeData[],
  filename: string = 'uptac_college_predictions.csv'
) => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = [
    'Serial No.',
    'Institute',
    'Program',
    'Quota',
    'Category',
    'Round',
    'Opening Rank',
    'Closing Rank'
  ];

  const rows: string[] = [];

  data.forEach((college, index) => {
    rows.push([
      index + 1,
      `"${college.institute}"`,
      `"${college.program}"`,
      college.quota,
      college.category,
      college.round,
      college.opening_rank,
      college.closing_rank
    ].join(','));

    // 🔁 Insert watermark every 10 rows
    if ((index + 1) % 10 === 0) {
      rows.push(',,"Generated by Tushar Bhardwaj",,,,,');
    }
  });

  const csvContent = [headers.join(','), ...rows].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');

  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportToPDF = (
  data: CollegeData[],
  filename: string = 'uptac_college_predictions.pdf'
) => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const doc = new jsPDF();
  doc.text('UPTAC 2026 Predictor - Counselling Report', 14, 15);
  doc.setFontSize(10);
  doc.text('Generated by Tushar Bhardwaj', 14, 22);

  const tableColumn = ["Rank", "Institute", "Program", "Quota", "Category", "R", "Opening", "Closing"];
  const tableRows: any[] = [];

  data.forEach((college, index) => {
    const rowData = [
      index + 1,
      college.institute.length > 25 ? college.institute.substring(0, 25) + '...' : college.institute,
      college.program.length > 20 ? college.program.substring(0, 20) + '...' : college.program,
      college.quota,
      college.category,
      college.round,
      college.opening_rank,
      college.closing_rank
    ];
    tableRows.push(rowData);
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 25,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [79, 70, 229] },
  });

  doc.save(filename);
};

export const printResults = () => {
  window.print();
};
